In [1]:
import numpy as np


np_list: object = np.array([1,2,3])

In [2]:
np_list

array([1, 2, 3])

In [3]:
print(np_list)

[1 2 3]


In [4]:
array_2d = np.array([
                     [56, 5.8, 120], 
                     [12, 6, 100],
                     [41, 5, 120],
                     [23, 5.7, 135]
                    ])

In [5]:
print(array_2d)

[[ 56.    5.8 120. ]
 [ 12.    6.  100. ]
 [ 41.    5.  120. ]
 [ 23.    5.7 135. ]]


In [16]:
array_3d = np.ones((2,2,3))

To find out dimention of the data use: .shape command

In [7]:
array_2d.shape

(4, 3)

To identify the data type of an array, use dtype.name

In [8]:
array_2d.dtype.name

'float64'

In [9]:
array_2d.size

12

In [10]:
array_3d.shape

(2, 2, 3)

In [17]:
print(array_3d)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [28]:
nextArray = np.arange(0,10,5)

In [29]:
nextArray.shape

(2,)

In [30]:
print(nextArray)

[0 5]


In [31]:
nextArray.size

2

In [32]:
anotherArray = np.linspace(0,10,50)

In [33]:
print(anotherArray)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [36]:
anotherArray.shape

(50,)

In [38]:
anotherArray.size

50

In [41]:
testArray1 = np.ones((3,4))

In [42]:
testArray1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
arr = np.arange(0,25)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
arr[8]

8

In [50]:
arr[0:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [52]:
arr[5:12]

array([ 5,  6,  7,  8,  9, 10, 11])

In [55]:
arr[-3:]

array([22, 23, 24])

In [57]:
arr[-1:-3]

array([], dtype=int32)

In [58]:
array_2d.shape

(4, 3)

In [60]:
array_2d[2][1]

5.0

In [61]:
array_2d[2,1]

5.0

In [63]:
array_2d[2]

array([ 41.,   5., 120.])

In [64]:
array_2d[2,:]

array([ 41.,   5., 120.])

In [65]:
array_2d[:2,1:3]

array([[  5.8, 120. ],
       [  6. , 100. ]])

In [67]:
array_2d[:,2]

array([120., 100., 120., 135.])

In [69]:
array_2d[:,1:3]

array([[  5.8, 120. ],
       [  6. , 100. ],
       [  5. , 120. ],
       [  5.7, 135. ]])

In [73]:
new_array_2d = array_2d.copy()

In [74]:
new_array_2d

array([[ 56. ,   5.8, 120. ],
       [ 12. ,   6. , 100. ],
       [ 41. ,   5. , 120. ],
       [ 23. ,   5.7, 135. ]])

In [77]:
new_array_2d[:,:] = 90

In [78]:
new_array_2d

array([[90., 90., 90.],
       [90., 90., 90.],
       [90., 90., 90.],
       [90., 90., 90.]])

In [79]:
new_array_2d[:,1:3] = 0

In [80]:
new_array_2d

array([[90.,  0.,  0.],
       [90.,  0.,  0.],
       [90.,  0.,  0.],
       [90.,  0.,  0.]])

In [81]:
a = np.sqrt(new_array_2d)

In [83]:
a

array([[9.48683298, 0.        , 0.        ],
       [9.48683298, 0.        , 0.        ],
       [9.48683298, 0.        , 0.        ],
       [9.48683298, 0.        , 0.        ]])

In [84]:
a = np.log(new_array_2d)

C:\Users\knn21\PycharmProjects\Basics\venv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


In [85]:
a

array([[4.49980967,       -inf,       -inf],
       [4.49980967,       -inf,       -inf],
       [4.49980967,       -inf,       -inf],
       [4.49980967,       -inf,       -inf]])

In [87]:
trans_array_2d = new_array_2d.T

In [90]:
new_array_2d.shape

(4, 3)

In [91]:
trans_array_2d.shape

(3, 4)